"""Add User model

Revision ID: 44d1002dea8c
Revises: fea72a8c7dde
Create Date: 2023-08-07 18:36:58.749457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d1002dea8c'
down_revision = 'fea72a8c7dde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
